---
title: "Homework 2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Aidan Hughes

Student \# 18045138

Tuesday, September 25, 2018

## Exploring the Gapminder Object

```{r}
library("gapminder")
library("tidyverse")

# Type/ class of the object
typeof(gapminder)
class(gapminder)

# Size of the object
nrow(gapminder)

ncol(gapminder)
# or
length(gapminder)

# Data type of each variable
str(gapminder)

```



## Exploring some Variables

Here we explore the Gapminder dataframe a bit and then look at the years data was taken, and the contries, individually.

```{r}
# Start of with summary of the full data frame
summary(gapminder)

# See how many unique years of data and the range of years
select(gapminder, year) %>%
  distinct() -> years
years
  
# See how many unique years there are and the range
years %>%
  { c(nrow(.), range(.)) } -> yearstats
yearstats

# Try the same for "country"
select(gapminder, country) %>%
  distinct() -> countries

countries
nrow(countries)


```

Next, we plot a distribution and violin plot, similar to what was done in class. We can also use the `filter` function to plot a smaller set of data.

```{r}

# As done in class, view the probability distribution for a variable
ggplot(gapminder, aes(lifeExp)) +
  geom_density() +
  geom_histogram(aes(y=..density..),fill='red', alpha=0.4)
  
filter(gapminder, year==1992) %>%
  ggplot(aes(continent, lifeExp)) +
  geom_violin()

filter(gapminder, continent=="Oceania", year==1992)
```


